### ISSUE TITLE
Unable to specifying secrets in atlas team

### ISSUE THREAD

**Issue by vmanikes** [mongodb/mongodb-atlas-kubernetes#1959]
**What did you do to encounter the bug?**
I have secrets for atlas in one namespace and am trying to create a AtlasTeam resource in another. Apparently the created resource is unable to reference secret in other namespace in default. Other resources such as atlasProject has support to reference cross NS secret. I was wondering if there is a way to do the same for AtlasTeam https://www.mongodb.com/docs/atlas/operator/current/atlasteam-custom-resource/ 

**Operator Information**
 - 2.5.0

**Comment by josvazg** [comment]
Hi @vmanikes, could you confirm what is the layout of your setup? what resources you have defined and in which namespace?

Note that teams do not work on their own right now, you need to define one or more Atlas Projects referencing them in order to be managed by the operator.

**Comment by vmanikes** [comment]
Ok that explains why I am not able to see teams in the UI. I will try referencing the team with a project
