### ISSUE TITLE
Add a mirror to docker.io 

### ISSUE THREAD

**Issue by cebidhem** [mongodb/mongodb-atlas-kubernetes#209]
Hi MongoDB team,

First I must say I'm quite happy to discover this operator! We are in the process of migrating our current infrastructure to Atlas and it was impossible to integrate it in our GitOps workflows, so we started with the terraform provider.. 
I guess this deserves more than a "hidden" section in the docs ;) 

I'm opening this issue because as you know, docker introduced rate limits for pulling images, and when managing a certain amount of k8s clusters this can become quickly an issue. 
Without moving away from dockerhub, would you consider setting up a mirror for your repo on another platform such as quay.io or gcr.io please ?

We can always pull and push the operator images on our private repo, but I guess it would be simpler for us (and probably for others) to have a mirror.

Thanks for this operator I'm really looking forward trying it!

**Comment by jamesbroadhead** [comment]
Hi @cebidhem - thanks for the report! 

We're using quay.io for other products - we'll start releasing the Atlas Operator there too shortly

**Comment by antonlisovenko** [comment]
Hi @cebidhem 

The quay.io image 0.5.0 is pushed and [ready](https://quay.io/repository/mongodb/mongodb-atlas-kubernetes-operator?tab=tags) for use.
We are working on changing our release pipeline to release both to dockerhub and quay.io

**Comment by cebidhem** [comment]
Thanks @antonlisovenko , we now pull from the quay.io repo and all is fine!

I leave the closing of the issue to you once the PR gets merged.
