### ISSUE TITLE
Randomly Generated Username And Password

### ISSUE THREAD

**Issue by alex-tw-lam** [mongodb/mongodb-atlas-kubernetes#231]
Currently, when we spin up an atlas cluster, it requires a static username and password.

Ideally, the helm chart should generate a random username/password pair upon cluster creation.

**Comment by jasonmimick** [comment]
We will add this to the helm chart in an upcoming release.

**Comment by bordeuax** [comment]
I will add from my side; that each time when we are creating a new user and `passwordSecretRef` is not specified will be very usefully to generate automatically a secret for password.

**Comment by jasonmimick** [comment]
This feature is now supported in the helm chart - see: https://github.com/mongodb/helm-charts/blob/40c089fdaf0cbe3367686e73a3e57667f065ebae/charts/atlas-cluster/templates/atlas-mongodb-user-secret.yaml#L13
