### ISSUE TITLE
Changes To Username Does Not Recycle Or Delete The Existing User

### ISSUE THREAD

**Issue by alex-tw-lam** [mongodb/mongodb-atlas-kubernetes#232]
Changes username from u8652cb31 to u8652cb3k end up with two different users from Atlas console. 

![image](https://user-images.githubusercontent.com/72969119/118614329-325f3100-b7f2-11eb-9c42-5631e32290a5.png)

**Comment by leo-ri** [comment]
Hello, @alex-tw-lam

I checked and it was fixed in CLOUDP-90707: Retry sending the delete request for DB users (#283), these changes were released in v0.6.1

Thank you for reporting
