### ISSUE TITLE
Database Name Missing From MongoDB Connection URL

### ISSUE THREAD

**Issue by alex-tw-lam** [mongodb/mongodb-atlas-kubernetes#238]
Database name should be part of the connection string to maintain a consistent user experience. 

When database user is first created. Database name is a mandatory field: 
```
Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(AtlasDatabaseUser.spec.roles[0]): missing required field "databaseName" in com.mongodb.atlas.v1.AtlasDatabaseUser.spec.roles
```

But the resultant connection string doesn't contain the database name: 
`mongodb+srv://u3e8127c4:********-********-********-********@cluster1-atlas-cluster.odgdx.mongodb.net/default`

Neither can the the database user create a another database, resulting in error: 
`pymongo.errors.OperationFailure: not authorized on mymongodb to execute command { find: "todo", filter: { done: "no" }, limit: 1, singleBatch: true, lsid: { id: UUID("10abc4cd-adb1-43d1-99ae-66776eaac296") }, $clusterTime: { clusterTime: Timestamp(1621847098, 1), si _172.17.0.1 - - [24/May/2021:09:05:07 +0000] "GET / HTTP/1.1" 500 290 "-" "kube-probe/1.19"
`

**Comment by jasonmimick** [comment]
Hi-
Database users and "Database Name" work a little differently on Atlas than in regular old MongoDB. In Atlas all scram/sha users are created in the "admin" database (since db-users are scoped to project level, by default users are shared by all db clusters in an Atlas project).  So here, it's actually trying to connect to a db called "default".

**Comment by alex-tw-lam** [comment]
Thanks for the update @jasonmimick  let me close the issue ticket.
