### ISSUE TITLE
Defaulting Webhook for IPAllowLists

### ISSUE THREAD

**Issue by Freyert** [mongodb/mongodb-atlas-kubernetes#266]
Would be great to have a defaulting webhook for IPAllowLists on projects so as to have the same list on all projects.

**Comment by jasonmimick** [comment]
Hi @Freyert -
Thanks for this idea and your feedback, we've added this to our official feature request list and will consider for a future release. Do you have any more requirements or perhaps an example of the scenario you're looking to support?

**Comment by Freyert** [comment]
As a cluster operator, I would like to enable namespace admins to create new projects, but be able to enforce a given set of IPAllowList rules.

On the other hand this may be something better handled by OpenPolicyAgent.

**Comment by jasonmimick** [comment]
@priyolahiri Do you have any examples with your recent OPA work you could share here? 

Thanks

**Comment by priyolahiri** [comment]
OPA could be a good fit for this sort of thing. We don't currently have examples for the Atlas Operator, but there are some basic example for the Enterprise Operator repo here [https://github.com/mongodb/mongodb-enterprise-kubernetes/tree/master/opa_examples]. It should be easy to look at the examples and create your own policy for the Atlas Operator.

**Comment by Freyert** [comment]
That's a great recommendation. I've looked at OPA for a while, but not used it yet. Closing this ticket in favor of that!
