### ISSUE TITLE
Update website documentation on removing dots from connection secret fields

### ISSUE THREAD

**Issue by denist-huma** [mongodb/mongodb-atlas-kubernetes#274]
The issue is that [website documentation](https://docs.atlas.mongodb.com/reference/atlas-operator/atlasdatabaseuser-custom-resource/#connection-secrets) says:

> Parameter | Description
connectionString.standard | Public mongodb:// connection URI.
connectionstring.standardSrv | Public mongodb+srv:// connection URI.

I found #241 the right connection secrets key names are now connectionStringStandard and connectionStringStandardSrv

Operator version v0.5.0

**Comment by jasonmimick** [comment]
We will update the docs along with the next release 0.6.0 of the operator, thanks for noting this.
