### ISSUE TITLE
Spurious Deletion Events for AtlasProject

### ISSUE THREAD

**Issue by Freyert** [mongodb/mongodb-atlas-kubernetes#335]
### Request
We were examining our logs this morning and noticed several instances of `"Starting AtlasProject deletion"` for `AtlasProjects` that have no corresponding `delete` request in our audit logs (from what we can see and know). Fortunately we have the annotation to prevent deletion, but we would rather have this not be something we see in our logs.

This behavior is consistent with other tickets we have seen on this board so we estimate this is a bug.

We've noticed it happens very infrequently, but on an almost regular schedule. I _imagine_ it might have to do with the SyncPeriod. However, it seems to only happen on Mondays and not every 3 hours 🤷 .

Summary:
1.  Can it be clarified if this is a known issue? Are there other related tickets?
2. Clarify the need to react to delete events outside of the reconcile loop.

------

### Investigation of the Code

Looking at other operators they seem to check if an object needs to be deleted during the `Reconcile` call and not via a specific watch for deletion events. I wager this leads to this unexpected consequence since this operator is short circuiting `controller-runtime` by adding deletion events directly to an informer.

Some examples:

* [ArgoCD Operator](https://github.com/argoproj-labs/argocd-operator/blob/master/controllers/argocd/argocd_controller.go#L85-L100)
* [Kubebuilder: _Using Finalizers_](https://book.kubebuilder.io/reference/using-finalizers.html)

From what I can tell, Reconcile gives them an object that has a [DeletionTimestamp](https://github.com/kubernetes/apimachinery/blob/57f2a0733447cfd41294477d833cce6580faaca3/pkg/apis/meta/v1/meta.go#L155) and then the process follows as documented in ["Kubernetes Blog: _Using Finalizers to Control Deletion_"](https://kubernetes.io/blog/2021/05/14/using-finalizers-to-control-deletion/).

Future Considerations:
1. Consider adding a finalizer to Atlas Custom Resources to prevent the Custom Resource from being deleted until the operator has finished cleaning up on the Atlas API.
2. Remove the [Deletion Event Watches](https://github.com/mongodb/mongodb-atlas-kubernetes/blob/main/pkg/controller/atlasproject/atlasproject_controller.go#L190-L200)

**Comment by Freyert** [comment]
We've been testing the latest locally and have noticed there _is_ a deletionTimeStamp being set. So something is triggering a real deletion event.

There may be two problems here:
1. With the annotation the resource will not be deleted from K8S so it will consistently loop onto this.
2. Something is adding deletion annotations. Perhaps it's something with helm 🤔

**Comment by fabritsius** [comment]
I haven't noticed these errors after the d531daa827d4254ed77c00ab456cfe47eca07b1e commit. We will try to reproduce what you are seeing.

A few questions:
- By the `latest` version do you mean the commit d531daa827d4254ed77c00ab456cfe47eca07b1e where we added finalizers for projects?
- Have you seen [this doc for helm upgrades](https://github.com/mongodb/helm-charts/blob/40c089fdaf0cbe3367686e73a3e57667f065ebae/charts/atlas-cluster/README.md#upgrade-notes)?
- Is the error infrequent as before or has something changed?

Thanks 🙏

**Comment by Freyert** [comment]
@fabritsius, we removed the helm hook annotations and it seems to function correctly. I think this was our issue all along!

**Comment by fabritsius** [comment]
Great, thank you for the feedback 😌
