### ISSUE TITLE
AtlasDBUser secret is missing a private connection string for a VPC-peered GCP or Azure

### ISSUE THREAD

**Issue by denist-huma** [mongodb/mongodb-atlas-kubernetes#347]
**What did you do to encounter the bug?**

Cannot connect from a VPC-peered GKE to Atlas using standard connection string given by AKO
Atlas KO gives a standard connection string.

```sh
$ kubectl run -i -t mongosh --image=bitnami/mongodb -- bash
^[OPIf you don't see a command prompt, try pressing enter.
I have no name!@mongosh:/$ mongo "mongodb+srv://my-cluster.l2l7u.gcp.mongodb.net" --username demo-user
MongoDB shell version v4.4.10
Enter password: 
connecting to: mongodb://my-cluster-shard-00-00.l2l7u.gcp.mongodb.net:27017,my-cluster-shard-00-01.l2l7u.gcp.mongodb.net:27017,my-cluster-shard-00-02.l2l7u.gcp.mongodb.net:27017/?###
{"t":{"$date":"2021-11-23T13:02:54.327Z"},"s":"I",  "c":"NETWORK",  "id":4333208, "ctx":"ReplicaSetMonitor-TaskExecutor","msg":"RSM host selection timeout","attr":{"replicaSet":"atlas-###-shard-0","error":"FailedToSatisfyReadPreference: Could not find host matching read preference { mode: \"nearest\" } for set atlas-###-shard-0"}}


*** You have failed to connect to a MongoDB Atlas cluster. Please ensure that your IP whitelist allows connections from your network.

Error: connect failed to replica set atlas-###-shard-0/my-cluster-shard-00-00.l2l7u.gcp.mongodb.net:27017,my-cluster-shard-00-01.l2l7u.gcp.mongodb.net:27017,my-cluster-shard-00-02.l2l7u.gcp.mongodb.net:27017 :
connect@src/mongo/shell/mongo.js:374:17
@(connect):2:6
exception: connect failed
exiting with code 1
```

**What did you expect?**

I expect to have a private string also present in a secret.
I can add -pri to "mongodb+srv://my-cluster-pri.l2l7u.gcp.mongodb.net/pp_dev" and do check.
The private string connection is successful. 

```sh
I have no name!@mongosh:/$ mongo "mongodb+srv://my-cluster-pri.l2l7u.gcp.mongodb.net/pp_dev" --username demo-user 
MongoDB shell version v4.4.10
Enter password: 
connecting to: mongodb://my-cluster-shard-00-00-pri.l2l7u.gcp.mongodb.net:27017,my-cluster-shard-00-01-pri.l2l7u.gcp.mongodb.net:27017,my-cluster-shard-00-02-pri.l2l7u.gcp.mongodb.net:27017/pp_dev?###
Implicit session: session { "id" : UUID("###") }
MongoDB server version: 4.2.17
WARNING: shell and server versions do not match
MongoDB Enterprise atlas-###-shard-0:PRIMARY>
```

> Clusters with peered networks have a Private IP for [Peering connection string][1]. This string resolves to IP addresses available to:
> 
> Peered networks in Azure or GCP
> AWS peered clusters with a custom DNS service.
> 
> [Private Connection Strings][1]
> Private connection strings follow this format:
> 
> mongodb://xyx456-shard-00-00-pri.ab123.mongodb.net:27017
> mongodb+srv://xyx456-pri.ab123.mongodb.net
> 

[1]: https://docs.atlas.mongodb.com/reference/faq/connection-changes/#private-connection-strings

**What happened instead?**
A clear and concise description of what happened instead

**Screenshots**

**Operator Information**
 - Operator Version 0.6.1

**Kubernetes Cluster Information**
 - Distribution GKE
 - Version v1.19.14-gke.1900
 - Image Registry location (quay, or an internal registry) quay.io/denistrofimov/mongodb-atlas-kubernetes:v0.6.1-dt

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by jhill072** [comment]
Would image version 0.7.0 provide what you are looking for? It includes this PR which adds the private connection string returned from the Atlas API as another key in the generated secret: https://github.com/mongodb/mongodb-atlas-kubernetes/pull/344

**Comment by denist-huma** [comment]
@jhill072 thanks for th PR! 
yes it is related to my request!
it is very good that you ping me because I don't see it in changes while I was updating to the 0.7.0.
Also  don't find it documented.
