### ISSUE TITLE
Support for Customer Managed Key on Project CRD

### ISSUE THREAD

**Issue by kkr2320** [mongodb/mongodb-atlas-kubernetes#395]
For enterprises heavily rely on tighter security , CMK is very essential and should be allowed to configure via the operator.  Given that Rest API is in place , the operator should support. 

Please update if there already an ETA for this feature available . 

Thanks

**Comment by jasonmimick** [comment]
Hello @kkr2320 -

Thanks for reporting this; we are reviewing internally, planning, and will revert shortly.

-Jason

**Comment by fabritsius** [comment]
This feature was added in the [release v1.3.0](https://github.com/mongodb/mongodb-atlas-kubernetes/releases/tag/v1.3.0).
Closing this for now.
Feel free to reopen in case there are any problems.
