### ISSUE TITLE
Sharding across multiple machines

### ISSUE THREAD

**Issue by iquerame2** [mongodb/mongodb-atlas-kubernetes#568]
I am trying to deploy sharding in a multi-machine setting, where each physical machine (VM) contains a different shard collection (potentially with replicas). In particular, is it possible not to have the same shard collection automatically replicated across all machines? Otherwise said, can we work with different database fragments on each machine?
Please tell me if you know some DBMS that ensure this setting.
Thank you!

**Comment by igor-karpukhin** [comment]
Hi @iquerame2. Thanks a lot for opening an issue, but this is not related to atlas-operator. Please recreate this issue for https://github.com/mongodb/mongodb-kubernetes-operator if you use community operator, or open a support ticket if you use the enterprise version.
