### ISSUE TITLE
localhost 8080 forbidden

### ISSUE THREAD

**Issue by Azaretdodo** [mongodb/mongodb-atlas-kubernetes#641]
**What did you do to encounter the bug?**
Steps to reproduce the behavior: **sudo kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-atlas-kubernetes/main/deploy/all-in-one.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?**

**What did you expect?**
A clear and concise description of what you expected to happen. **i may launch the first line of command without errors**

**What happened instead?**
A clear and concise description of what happened instead : **the server is forbidden**

**Screenshots**

**Operator Information**
 - Operator Version : **kubectl 1.24.3**

**Kubernetes Cluster Information**
 - Distribution **ubuntu 22.04 kinetic
 - Version kubernetes --version
1.0.0**
 - Image Registry location (quay, or an internal registry) i don't reach this step

**Additional context**

If possible, please include:
 - `kubectl describe` output **sudo kubectl api-resources
NAME   SHORTNAMES   APIVERSION   NAMESPACED   KIND
The connection to the server localhost:8080 was refused - did you specify the right host or port?**

 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by igor-karpukhin** [comment]
@Azaretdodo is there a reason you run `kubectl` with sudo? It looks like you have no context configured. What does `kubectl config view` shows you (any clusters listed)?

**Comment by Azaretdodo** [comment]
the answer of your line of command asked below :

'''kubectl config view
apiVersion: v1
clusters: null
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null
'''

if i launch without sudo that reach the same error :

''':~/programs/mongodb-atlas-kubernetes$ kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-atlas-kubernetes/main/deploy/all-in-one.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?
'''

thanks you in advance for your help,

regards.


Azaretdodo.
________________________________
De : Igor Karpukhin ***@***.***>
Envoyé : samedi 13 août 2022 20:50
À : mongodb/mongodb-atlas-kubernetes ***@***.***>
Cc : Azaretdodo ***@***.***>; Mention ***@***.***>
Objet : Re: [mongodb/mongodb-atlas-kubernetes] localhost 8080 forbidden (Issue #641)


@Azaretdodo<https://github.com/Azaretdodo> is there a reason you run kubectl with sudo? It looks like you have no context configured. What does kubectl config view shows you (any clusters listed)?

**Comment by igor-karpukhin** [comment]
@Azaretdodo you have to connect to the cluster first, before running `kubectl apply -f ...`

**Comment by Azaretdodo** [comment]
Does this is explained in the full documentation how to do ?

Thanks you in advance for your answer,

Regards.


Dorian Rosse.
________________________________

**Comment by igor-karpukhin** [comment]
@Azaretdodo The docs assume that you already have a running Kubernetes cluster. If you want to test the operator locally, you can create a Kubernetes cluster locally either with minikube or kind: 
https://minikube.sigs.k8s.io/docs/start/
https://kind.sigs.k8s.io/docs/user/quick-start/#installation

**Comment by Azaretdodo** [comment]
thanks you for your link because i success to go more far however i got a new error after this line of command thus i copy paste below :

''':~/programs/mongodb-atlas-kubernetes$ sudo kubectl create secret generic mongodb-atlas-operator-api-key \
         --from-literal="orgId=<the_atlas_organization_id>" \
         --from-literal="publicApiKey=<the_atlas_api_public_key>" \
         --from-literal="privateApiKey=<the_atlas_api_private_key>" \
         -n mongodb-atlas-system

kubectl label secret mongodb-atlas-operator-api-key atlas.mongodb.com/type=credentials -n mongodb-atlas-system
secret/mongodb-atlas-operator-api-key created
error: cluster "minikube" does not exist
'''

if i remove the alias with unalias i got the error who did publish my error to the support github thus i don't understand what way from both follow :

'''~/programs/mongodb-atlas-kubernetes$ unalias kubectl
:~/programs/mongodb-atlas-kubernetes$ sudo kubectl create secret generic mongodb-atlas-operator-api-key \
         --from-literal="orgId=<the_atlas_organization_id>" \
         --from-literal="publicApiKey=<the_atlas_api_public_key>" \
         --from-literal="privateApiKey=<the_atlas_api_private_key>" \
         -n mongodb-atlas-system

kubectl label secret mongodb-atlas-operator-api-key atlas.mongodb.com/type=credentials -n mongodb-atlas-system
error: failed to create secret secrets "mongodb-atlas-operator-api-key" already exists
The connection to the server localhost:8080 was refused - did you specify the right host or port?
'''

thanks you in advance to help myself follow the good path for install the program mongodb on kubernetes,

regards.


Azaretdodo.
________________________________
De : Igor Karpukhin ***@***.***>
Envoyé : samedi 13 août 2022 21:49
À : mongodb/mongodb-atlas-kubernetes ***@***.***>
Cc : Azaretdodo ***@***.***>; Mention ***@***.***>
Objet : Re: [mongodb/mongodb-atlas-kubernetes] localhost 8080 forbidden (Issue #641)


@Azaretdodo<https://github.com/Azaretdodo> The docs assume that you already have a running Kubernetes cluster. If you want to test the operator locally, you can create a Kubernetes cluster locally either with minikube or kind:
https://minikube.sigs.k8s.io/docs/start/
https://kind.sigs.k8s.io/docs/user/quick-start/#installation

**Comment by Azaretdodo** [comment]
now i have build kubernetes i got a new error below : 

`error: failed to create secret namespaces "mongodb-atlas-system" not found`


```
:~/programs/mongodb-atlas-kubernetes$ sudo kubectl create secret generic mongodb-atlas-operator-api-key \
         --from-literal="orgId=<the_atlas_organization_id>" \
         --from-literal="publicApiKey=<the_atlas_api_public_key>" \
         --from-literal="privateApiKey=<the_atlas_api_private_key>" \
         -n mongodb-atlas-system

kubectl label secret mongodb-atlas-operator-api-key atlas.mongodb.com/type=credentials -n mongodb-atlas-system
error: failed to create secret namespaces "mongodb-atlas-system" not found
The connection to the server localhost:8080 was refused - did you specify the right host or port?
:~/programs/mongodb-atlas-kubernetes$ cat <<EOF | kubectl apply -f -
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: my-project
spec:
  name: Test Atlas Operator Project
  projectIpAccessList:
    - ipAddress: "192.0.2.15"
      comment: "IP address for Application Server A"
    - ipAddress: "203.0.113.0/24"
      comment: "CIDR block for Application Server B - D"
EOF
The connection to the server localhost:8080 was refused - did you specify the right host or port?

```

thanks you in advance to help myself fully install mogodb,

Regards.


Azaretdodo.

**Comment by igor-karpukhin** [comment]
@Azaretdodo you have to create a namespace first with `kubectl create namespace mongodb-atlas-system`

**Comment by Azaretdodo** [comment]
now i have reach more far unfornately i got a new error however this isn't my application thus this is maybe good finaly the line of error with the error below : 

`:~/programs/mongodb-atlas-kubernetes$ sudo cat <<EOF | sudo kubectl apply -f -
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: my-project
spec:
  name: Test Atlas Operator Project
  projectIpAccessList:
    - ipAddress: "192.0.2.15"
      comment: "IP address for Application Server A"
    - ipAddress: "203.0.113.0/24"
      comment: "CIDR block for Application Server B - D"
EOF
error: resource mapping not found for name: "my-project" namespace: "" from "STDIN": no matches for kind "AtlasProject" in version "atlas.mongodb.com/v1"
ensure CRDs are installed first
`

thanks you in advance to help myself finish mongodb,

Regards.


Azaretdodo.

**Comment by igor-karpukhin** [comment]
@Azaretdodo I'm not sure I follow what are you trying to do. Here is a quick start guide:
1. Create a local cluster using either minikube or kind. (E.g. `minikube start`)
2. Run `kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-atlas-kubernetes/main/deploy/all-in-one.yaml`. (example output: ```
namespace/mongodb-atlas-system created
customresourcedefinition.apiextensions.k8s.io/atlasbackuppolicies.atlas.mongodb.com created
customresourcedefinition.apiextensions.k8s.io/atlasbackupschedules.atlas.mongodb.com created
customresourcedefinition.apiextensions.k8s.io/atlasdatabaseusers.atlas.mongodb.com created
customresourcedefinition.apiextensions.k8s.io/atlasdeployments.atlas.mongodb.com created
customresourcedefinition.apiextensions.k8s.io/atlasprojects.atlas.mongodb.com created
serviceaccount/mongodb-atlas-operator created
role.rbac.authorization.k8s.io/mongodb-atlas-leader-election-role created
clusterrole.rbac.authorization.k8s.io/mongodb-atlas-manager-role created
rolebinding.rbac.authorization.k8s.io/mongodb-atlas-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/mongodb-atlas-manager-rolebinding created
deployment.apps/mongodb-atlas-operator created```)
3. Check if you have the operator running in the `mongodb-atlas-system` namespace: `kubectl -n mongodb-atlas-system get pods` (example output: ```mongodb-atlas-operator-8574fc879f-clmkv   1/1     Running   0          116s```)

**Comment by Azaretdodo** [comment]
i went to launch the deployement example from the readme i paste the line of command below however if you have any or some goods and smarts example i will be happy : 

`:~$ sudo cat <<EOF | sudo kubectl apply -f -
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: my-project
spec:
  name: Test Atlas Operator Project
  projectIpAccessList:
    - ipAddress: "192.0.2.15"
      comment: "IP address for Application Server A"
    - ipAddress: "203.0.113.0/24"
      comment: "CIDR block for Application Server B - D"
EOF
[sudo] Mot de passe de dorianrosse : 
atlasproject.atlas.mongodb.com/my-project created
`

if you haven't any example it isn't bad we can close the issue,

thanks you in advance if you have any or some goods and smarts example,

regards.


Azaretdodo.

**Comment by Azaretdodo** [comment]
before close the issue unfornately i got a new error below : 

`sudo kubectl get atlasdatabaseusers my-database-user -o=jsonpath='{.status.conditions[?(@.type=="Ready")].status}'
True
FalseLa commande « True » n'a pas été trouvée, voulez-vous dire :
  commande « rue » du snap darkdimension-rue (0.3.0)
  commande « true » du deb coreutils (8.32-4.1ubuntu1)
Voir « snap info <nomdusnap> » pour des versions supplémentaires.
:~$ sudo kubectl get atlasdatabaseusers my-database-user -o=jsonpath='{.status.conditions[?(@.type=="Ready")].status}' \
> true
Error from server (NotFound): atlasdatabaseusers.atlas.mongodb.com "true" not found
:~$ sudo snap install true
erreur : snap "true" non trouvé
:~$ sudo apt-get install true
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
E: Impossible de trouver le paquet true
:~$ sudo apt-get install coreutils
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
coreutils est déjà la version la plus récente (8.32-4.1ubuntu1).
coreutils passé en « installé manuellement ».
0 mis à jour, 0 nouvellement installés, 0 à enlever et 3 non mis à jour.
:~$ sudo snap install coreutils
erreur : snap "coreutils" non trouvé
`

thanks you in advance to help myself fully use mongodb,

regards.


Azaretdodo.

**Comment by igor-karpukhin** [comment]
@Azaretdodo this is the command `sudo kubectl get atlasdatabaseusers my-database-user -o=jsonpath='{.status.conditions[?(@.type=="Ready")].status}`. The `true` after it in the Readme file, is just an example of the output.

**Comment by Azaretdodo** [comment]
this feed is long unfornately this isn't finish because i got new error below : 

''':~/programs/mongodb-atlas-kubernetes$ ...
containers:
- name: test-app
  env:
    - name: "CONNECTION_STRING"
      valueFrom:
        secretKeyRef:
          name: test-atlas-operator-project-test-cluster-theuser
          key: connectionStringStandardSrv
... : commande introuvable
containers: : commande introuvable
- : commande introuvable
La commande « env: » n'a pas été trouvée, voulez-vous dire :
  commande « env » du deb coreutils (8.32-4.1ubuntu1)
  commande « env2 » du deb env2 (1.1.0-4)
Essayez : sudo apt install <nom du deb>
- : commande introuvable
valueFrom: : commande introuvable
secretKeyRef: : commande introuvable
La commande « name: » n'a pas été trouvée, voulez-vous dire :
  commande « namei » du deb util-linux (2.37.2-4ubuntu3)
  commande « named » du deb bind9 (1:9.18.1-1ubuntu1.1)
Essayez : sudo apt install <nom du deb>
La commande « key: » n'a pas été trouvée, voulez-vous dire :
  commande « key » du deb donkey (1.2.0-6)
  commande « keyd » du deb onak (0.6.1-1)
Essayez : sudo apt install <nom du deb>
'''

how to pass thoses errors ?

thanks you in advance for your time,

Regards.


Azaretdodo.

**Comment by igor-karpukhin** [comment]
@Azaretdodo please post the actual command that you trying to run

**Comment by Azaretdodo** [comment]
i try to create a password strong unfornately thoses line of command break thus i copy paste the line of command finaly without my own password this is juste for paste the line of command securely : 

`kubectl create secret generic the-user-password --from-literal="password=P@@sword%"

kubectl label secret the-user-password atlas.mongodb.com/type=credentials`

how to secure mongodb ?

thanks you in advance for your time to help,

regards.


Azaretdodo.

**Comment by igor-karpukhin** [comment]
@Azaretdodo what is the error from these commands do you see? Try to execute them one by one

**Comment by igor-karpukhin** [comment]
@Azaretdodo Could you please provide a complete output including the command that fails for you?

**Comment by igor-karpukhin** [comment]
@Azaretdodo But do you see the secret created in your namespace?

**Comment by Azaretdodo** [comment]
I haven't checked inside,

Thanks you in advance for your answer,

Regards.


Azatetdodo.
________________________________

**Comment by Azaretdodo** [comment]
You close too early,

How to set up another password?

I open a new ticket,

Regards.


Azatetdodo.
________________________________

**Comment by Azaretdodo** [comment]
Dear Igor,


You close too early because localhost problem is back,

Thanks you in advance to reopen the ticket,

Regards.


Azatetdodo.
________________________________

**Comment by Azaretdodo** [comment]
all is good :

'''sudo kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-atlas-kubernetes/main/deploy/all-in-one.yaml
[sudo] Mot de passe de dorianrosse :
Warning: resource namespaces/mongodb-atlas-system is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
namespace/mongodb-atlas-system configured
customresourcedefinition.apiextensions.k8s.io/atlasbackuppolicies.atlas.mongodb.com created
customresourcedefinition.apiextensions.k8s.io/atlasbackupschedules.atlas.mongodb.com created
customresourcedefinition.apiextensions.k8s.io/atlasdatabaseusers.atlas.mongodb.com created
customresourcedefinition.apiextensions.k8s.io/atlasdeployments.atlas.mongodb.com created
customresourcedefinition.apiextensions.k8s.io/atlasprojects.atlas.mongodb.com created
serviceaccount/mongodb-atlas-operator created
role.rbac.authorization.k8s.io/mongodb-atlas-leader-election-role created
clusterrole.rbac.authorization.k8s.io/mongodb-atlas-manager-role created
rolebinding.rbac.authorization.k8s.io/mongodb-atlas-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/mongodb-atlas-manager-rolebinding created
deployment.apps/mongodb-atlas-operator created
:~$ sudo kubectl -n mongodb-atlas-system get pods
NAME                                      READY   STATUS              RESTARTS   AGE
mongodb-atlas-operator-7c4bff4bfc-hbl9d   0/1     ContainerCreating   0          37s
'''

where i can find a good and smart cluster with the big kubernetes around mongodb by kubernetes ?

thanks you in advance for your answer,

Regards.


Azaretdodo.

________________________________
De : Igor Karpukhin ***@***.***>
Envoyé : dimanche 14 août 2022 16:46
À : mongodb/mongodb-atlas-kubernetes ***@***.***>
Cc : Azaretdodo ***@***.***>; Mention ***@***.***>
Objet : Re: [mongodb/mongodb-atlas-kubernetes] localhost 8080 forbidden (Issue #641)


@Azaretdodo<https://github.com/Azaretdodo> I'm not sure I follow what are you trying to do. Here is a quick start guide:

  1.  Create a local cluster using either minikube or kind. (E.g. minikube start)
  2.  Run kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-atlas-kubernetes/main/deploy/all-in-one.yaml. (example output: namespace/mongodb-atlas-system created customresourcedefinition.apiextensions.k8s.io/atlasbackuppolicies.atlas.mongodb.com created customresourcedefinition.apiextensions.k8s.io/atlasbackupschedules.atlas.mongodb.com created customresourcedefinition.apiextensions.k8s.io/atlasdatabaseusers.atlas.mongodb.com created customresourcedefinition.apiextensions.k8s.io/atlasdeployments.atlas.mongodb.com created customresourcedefinition.apiextensions.k8s.io/atlasprojects.atlas.mongodb.com created serviceaccount/mongodb-atlas-operator created role.rbac.authorization.k8s.io/mongodb-atlas-leader-election-role created clusterrole.rbac.authorization.k8s.io/mongodb-atlas-manager-role created rolebinding.rbac.authorization.k8s.io/mongodb-atlas-leader-election-rolebinding created clusterrolebinding.rbac.authorization.k8s.io/mongodb-atlas-manager-rolebinding created deployment.apps/mongodb-atlas-operator created)
  3.  Check if you have the operator running in the mongodb-atlas-system namespace: kubectl -n mongodb-atlas-system get pods (example output: mongodb-atlas-operator-8574fc879f-clmkv 1/1 Running 0 116s)
