### ISSUE TITLE
how to set up another password for mongodb

### ISSUE THREAD

**Issue by Azaretdodo** [mongodb/mongodb-atlas-kubernetes#644]
**What did you do to encounter the bug?**

I use the line of command below but I won't give my password thus this is as the readme finally try by your side to replace one word by your password:

```
kubectl create secret generic the-user-password --from-literal="password=P@@sword%"
kubectl label secret the-user-password atlas.mongodb.com/type=credentials
```

**What did you expect?**
i want secure the database mongodb by my own password

**What happened instead?**

`bash: someCharactereWhoFailTheProgram: event not found`

**Screenshots**

**Operator Information**
 - Operator Version : i use kubernetes as a operator for mongodb i don't use one of both kind or minikube who happen both localhost forbidden

**Kubernetes Cluster Information**
 - Distribution ubuntu 22.04 jammy
 - Version : :~$ kubernetes --version
1.0.0

 - Image Registry location (quay, or an internal registry) : i use the database set up from the reame mongodb by kubernete atlas

**Additional context**

If possible, please include:
 - `kubectl describe` output `
kubectl describe
error: You must specify the type of resource to describe. Use "kubectl api-resources" for a complete list of supported resources.
kubectl api-resources
NAME   SHORTNAMES   APIVERSION   NAMESPACED   KIND
The connection to the server localhost:8080 was refused - did you specify the right host or port?
`

 - yaml definitions for your objects : i haven't my own database
 - log files for the operator and database pods :  thanks you in advance if you need the logs to say from where they are

**Comment by Sugar-pack** [comment]
Hello, @Azaretdodo. Could you please use ' (single quotes) instead of double quotes? This should help. If not, please let me know.

**Comment by Azaretdodo** [comment]
Thanks you for your help but this isn't the help I need

**Comment by Sugar-pack** [comment]
I'm talking about the fact that it is better to use single quotes in bash commands if special characters are used. For example `kubectl create secret generic the-user-password --from-literal='password=P@@sword%'` instead of `kubectl create secret generic the-user-password --from-literal="password=P@@sword%"`
Could you please try it?

**Comment by Azaretdodo** [comment]
now i am got this error : 

'~$ sudo kubectl create secret generic the-user-password --from-literal='password=mypassword'
error: failed to create secret secrets "the-user-password" already exists'

how to change the password ?

thanks you in advance for your answer,

Regards.


Azaretdodo.

**Comment by Sugar-pack** [comment]
The easiest way is to delete the secret. And then recreate it.
`kubectl delete secret the-user-password`
`kubectl create secret generic the-user-password --from-literal='password=mypassword'`
You can find more information about secrets here: https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/
https://kubernetes.io/docs/concepts/configuration/secret/
