### ISSUE TITLE
1.2.0 unable to apply backupschedule

### ISSUE THREAD

**Issue by mattsmith-x** [mongodb/mongodb-atlas-kubernetes#660]
**What did you do to encounter the bug?**
Added spec.backupRef to AtlasDeployment that references a backupSchedule

**What did you expect?**
Expected reconciliation.

**What happened instead?**
`controller logs message":"can't delete сurrent backupschedule. got an empty response from the api: <nil>" `

**Screenshots**

**Operator Information**
 - 1.2.0

**Kubernetes Cluster Information**
`Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10-gke.600", GitCommit:"2c921d7b040ed9c5a3a1f9407fb109b74d72d0a4", GitTreeState:"clean", BuildDate:"2022-06-02T09:20:24Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}`

**Additional context**

If possible, please include:
[atlasbackupschedule-test.yaml.txt](https://github.com/mongodb/mongodb-atlas-kubernetes/files/9446955/atlasbackupschedule-test.yaml.txt)
[atlasdeployment-test.yaml.txt](https://github.com/mongodb/mongodb-atlas-kubernetes/files/9446958/atlasdeployment-test.yaml.txt)

**Comment by Sugar-pack** [comment]
Hello @mattsmith-x. Thank you for creating the issue. May you please attach related operator logs (last 50-100 lines before error)? And could you please clarify whether does operator is stuck in continuous reconciliation because of this error or not?

**Comment by mattsmith-x** [comment]
Closing. This issue was caused by not having an API Access List set on the Operator API Key. Once I added Operator IP to the API Access List, reconciliation of BackupSchedule completed.

**Comment by mattsmith-x** [comment]
> Hello @mattsmith-x. Thank you for creating the issue. May you please attach related operator logs (last 50-100 lines before error)? And could you please clarify whether does operator is stuck in continuous reconciliation because of this error or not?

Operator was stuck in continuous reconciliation during the condition.
