### ISSUE TITLE
Documentation Request: Example AtlasProject Prometheus Integration

### ISSUE THREAD

**Issue by mattsmith-x** [mongodb/mongodb-atlas-kubernetes#670]
Hi Atlas Operator Team:

Can you please share an example AtlasProject configured with a Prometheus Integration? I'm not clear how to pass a password. When I use secretRef and passwordRef with the corresponding name and namespace the Operator logs that it can't find the secret.

```spec:
  integrations:
  - enabled: true
    serviceDiscovery: http
    type: PROMETHEUS
    username: prom_user_123```

**Comment by fabritsius** [comment]
Hey @mattsmith-x,

The most likely cause is that you haven't labeled your secret like this (change `<names>` to yours):
```
kubectl create secret generic <prometheus-secret-name> --from-literal="password=shallnotpass"
kubectl label secret <prometheus-secret-name> atlas.mongodb.com/type=credentials
```
Add ` -n <secret-namespace>` to both commands if necessary.


You can find the [example prometheus integration here](https://www.mongodb.com/docs/atlas/reference/atlas-operator/atlasproject-custom-resource/#prometheus-example).

**Comment by mattsmith-x** [comment]
Thank you @fabritsius. This works, provided the secret is in the same namespace as my Project. I updated the support case requesting the Integration example be updated to include an example secret showing the required label.
