### ISSUE TITLE
Feature request: Allow abandon Atlas resource on K8s resource removal

### ISSUE THREAD

**Issue by zelig81** [mongodb/mongodb-atlas-kubernetes#840]
**What did you do to encounter the bug?**
After removal of k8s resource there is no way to leave Atlas resource (in GitOps way)

**What did you expect?**
Feature request: add possibility to abandon Atlas resource after removal k8s resource

**Operator Information**
 - Operator Version: 1.5.1

**Comment by helderjs** [comment]
Hi @zelig81!

This is already possible with the usage of the annotation `mongodb.com/atlas-resource-policy` on the CR you want to keep on Atlas. See [Annotation chapter](https://github.com/mongodb/mongodb-atlas-kubernetes/blob/main/docs/annotations.md) in our docs.

**Comment by fabritsius** [comment]
Here is also the related [section in the docs](https://www.mongodb.com/docs/atlas/reference/atlas-operator/custom-resources/#use-annotations-to-skip-deletion-or-reconciliation).

**Comment by zelig81** [comment]
@helderjs thank you very much - I did not found that from the first reading of documentation :(
