### ISSUE TITLE
Removal of k8s manifests is too quick

### ISSUE THREAD

**Issue by zelig81** [mongodb/mongodb-atlas-kubernetes#853]
**What did you do to encounter the bug?**
- the action of removal of all the set (Project/Deployment) - removes k8s manifest (almost immidiately) while Atlas resources are still in process. No annotation for keeping Atlas resources is not added. What will happen if the process will be cancelled by some reson on Atlas side?

**What did you expect?**
- removal of k8s resources should be finalized on real success of Atlas resources removal. 
- Operator should not start removal of dependants before dependencies will be finally removed on Atlas

**What happened instead?**
A clear and concise description of what happened instead
- k8s resources (all: Project/Deployment) are removed almost immidiately

**Operator Information**
 - Operator Version: v1.5.1

**Kubernetes Cluster Information**
 - Distribution: k3d
 - Version: 1.24
 - Image Registry location: default one

**Comment by igor-karpukhin** [comment]
Hi @zelig81. For the operator - the source of truth are CRs, not the status in the Atlas. If one removes a project/cluster in Atlas without removing CRs - the operator will immediately try to recreate them. But yes, I see your case, when someone tries to remove a project, for example, with active PrivateEndpoints, the project won't be deleted from Atlas.
